version: "3"

services:
  gomgo:
    image: golang_env_from_gomgo
    volumes:
      - ../:/go/src/github.com/curtank/gomongoengine
      - .:/trp
    working_dir: /go/src/github.com/curtank/gomongoengine
    network_mode: "host"
    command: "sh /trp/loop.sh"
    expose:
      - "5000"
